# Generated by Django 3.2.8 on 2022-01-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220115_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saleType',
            field=models.CharField(choices=[('Online Sale', 'Online Sale'), ('Offline Sale', 'Offline Sale')], default='Offline Sale', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderProducts', to='home.order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderProducts', to='home.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
