# Generated by Django 3.2.8 on 2022-01-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220124_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderState',
            field=models.CharField(choices=[('Dine in', 'Dine in'), ('Takeaway', 'Takeaway')], default='Dine in', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Amazon Pay', 'Amazon Pay'), ('Google Pay', 'Google Pay'), ('Paytm', 'Paytm'), ('Card', 'Card')], default='Cash', max_length=15),
        ),
    ]
