# Generated by Django 3.2.8 on 2022-02-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_expense_expensetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_split',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paument1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paument2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method2',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Amazon Pay', 'Amazon Pay'), ('Google Pay', 'Google Pay'), ('Paytm', 'Paytm'), ('Card', 'Card')], max_length=15, null=True),
        ),
    ]
