# Generated by Django 3.2.8 on 2022-02-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220204_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paument1',
            new_name='payment1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paument2',
            new_name='payment2',
        ),
    ]
