# Generated by Django 3.2.8 on 2022-02-07 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220205_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
