# Generated by Django 3.2.8 on 2022-02-07 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_expense_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_created',
            field=models.DateField(default=datetime.date(2022, 2, 7)),
        ),
    ]
