# Generated by Django 3.2.8 on 2022-02-07 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_expense_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 2, 7, 13, 26, 2, 916830, tzinfo=utc)),
        ),
    ]
