# Generated by Django 3.2.8 on 2022-02-07 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_expense_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
